Simulate
tawheeler/AutomotiveDrivingModels.jl pull request #42
Opened 2019-10-30 18:43 UTC by MaximeBouton

Change the `simulate!` function to return a vector of scenes. The function is faster, type stable, and the vector of scenes is easier to manipulate than the `QueueRecord` object.

2019-10-30 23:27 UTC, mattuntergassmair requested changes

2019-10-30 23:27 UTC, mattuntergassmair commented on src/behaviors/tim_2d_driver.jl
> +Base.rand(rng::AbstractRNG, driver::Tim2DDriver) = LatLonAccel(rand(driver.mlat), rand(driver.mlon).a)
we should pass on `rng` to `rand()` calls on rhs, right?

2019-10-30 23:27 UTC, mattuntergassmair commented on src/simulation/callbacks.jl
> -function _run_callbacks(callbacks::C, rec::EntityQueueRecord{S,D,I}, roadway::R, models::Dict{I,M}, tick::Int) where {S,D,I,R,M<:DriverModel,C<:Tuple{Vararg{Any}}}
Maybe we still need the `QueueRecord` version while `rec` is not deprecated?

2019-10-30 23:27 UTC, mattuntergassmair commented on src/simulation/simulation.jl
> +            push!(scenes[tick + 1], Entity(veh_state_p, veh.def, veh.id))
can we use `fill!` and indexing `[i]` instead of `empty!` and `push!`? May be more efficient and kind of feels cleaner to me

2019-10-30 23:27 UTC, mattuntergassmair commented on src/simulation/simulation.jl
> +    scenes::Vector{Frame{E}} = [Frame(E, length(scene)) for i=1:nticks+1],
I think I would prefer initialization of `scenes` as `Vector(Frame(E, length(scene)), nticks+1)` rather than list comprehension.

2019-10-30 23:27 UTC, mattuntergassmair commented on src/simulation/simulation.jl
> +            final_tick = tick + 1
we could probably get rid of the `final_tick` variable alltogether by using `scenes = scenes[1:tick+1]` here (or some other function for deleting remaining entries, ideally something that does not allocate new memory for scenes) and then simply returning `return scenes` at the end.

2019-10-30 23:27 UTC, mattuntergassmair commented on test/test_simulation.jl
> +    simulate!(scene, roadway, models, n_steps, dt, callbacks=(CollisionCallback(),))
do we want to call both versions of `simulate` here? what exactly is being tested? Maybe at least test type stability with `@inferred`

2019-10-30 23:27 UTC, mattuntergassmair commented on src/behaviors/lane_change_models.jl
>  abstract type LaneChangeModel end
shouldn't `LaneChangeModel` also inherit from `<: DriverModel`? If yes, we can drop the `Base.rand` implementations which are already implemented for `DriverModel`.

2019-10-30 23:27 UTC, mattuntergassmair commented on src/behaviors/lateral_driver_models.jl
> +Base.rand(model::LateralDriverModel) = rand(Random.GLOBAL_RNG, model)
Same as above - we should be able to just have `LateralDriverModel <: DriverModel` and drop implementations of `rand`

2019-10-31 16:46 UTC, MaximeBouton commented on src/simulation/simulation.jl
> +            push!(scenes[tick + 1], Entity(veh_state_p, veh.def, veh.id))
Actually the `push!` function on the `Frame` objects is not allocating: https://github.com/sisl/Records.jl/blob/master/src/frames.jl#L56

I also thought `fill!` would be cleaner but it creates reference to the same scene object.

2019-10-31 16:46 UTC, MaximeBouton commented on src/behaviors/tim_2d_driver.jl
> +Base.rand(rng::AbstractRNG, driver::Tim2DDriver) = LatLonAccel(rand(driver.mlat), rand(driver.mlon).a)
thanks for catching that!

2019-10-31 16:49 UTC, MaximeBouton commented on src/behaviors/lane_change_models.jl
>  abstract type LaneChangeModel end
agreed

2019-10-31 16:55 UTC, MaximeBouton commented on src/simulation/simulation.jl
> +            final_tick = tick + 1
I am not a fan of deleting entries, since scenes can be given in arguments, would `return scenes[1:tick+1]` in the if statement work?

2019-10-31 17:23 UTC, MaximeBouton commented on src/simulation/simulation.jl
> +    scenes::Vector{Frame{E}} = [Frame(E, length(scene)) for i=1:nticks+1],
This does not seem to work, I tried using `fill` as well but it copies the frame by reference.

2019-10-31 17:33 UTC, MaximeBouton commented on test/test_simulation.jl
> +    simulate!(scene, roadway, models, n_steps, dt, callbacks=(CollisionCallback(),))
I updated the tests, now it is checking that the callback is actually called and that the list of scenes is smaller than expected.

2019-10-31 17:34 UTC, raunakbh92 reviewed
This is an awesome idea! In fact, I was not using `simulate!` in my work and instead just running a loop that calls `get_actions!` and `tick!` and then pushes the updated `scene` into a list of scenes because the `Queuerecord` made my head hurt. So, this is brilliant. I am not a software engineering wizard like y'all so I don't have specific feedback on code speed or coding standards.

Also, it is great that now we have `using Random` within `AutomotiveModels.jl`.

2019-10-31 17:35 UTC, MaximeBouton commented
@raunakbh92 if you are not using `QueueRecords` anymore we should probably make a bigger PR to deprecate it.

2019-10-31 17:40 UTC, mattuntergassmair commented on src/simulation/simulation.jl
> +            final_tick = tick + 1
yes, even better I'd say

2019-10-31 17:48 UTC, raunakbh92 commented
I am using the `Trajdata` type for working with `NGSIM.jl`. Not sure if that is dependent on `QueueRecords`?

2019-10-31 20:29 UTC, merged